// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileTrans.proto

package org.gilmour.gos.pb;

public final class FileTransProto {
  private FileTransProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommonFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.CommonFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string FileID = 1;</code>
     */
    boolean hasFileID();
    /**
     * <code>required string FileID = 1;</code>
     */
    java.lang.String getFileID();
    /**
     * <code>required string FileID = 1;</code>
     */
    com.google.protobuf.ByteString
        getFileIDBytes();

    /**
     * <code>required int64 FileSize = 2;</code>
     */
    boolean hasFileSize();
    /**
     * <code>required int64 FileSize = 2;</code>
     */
    long getFileSize();

    /**
     * <code>required bytes FileData = 3;</code>
     */
    boolean hasFileData();
    /**
     * <code>required bytes FileData = 3;</code>
     */
    com.google.protobuf.ByteString getFileData();
  }
  /**
   * Protobuf type {@code pb.CommonFile}
   */
  public  static final class CommonFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.CommonFile)
      CommonFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommonFile.newBuilder() to construct.
    private CommonFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommonFile() {
      fileID_ = "";
      fileData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommonFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fileID_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fileSize_ = input.readInt64();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              fileData_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gilmour.gos.pb.FileTransProto.internal_static_pb_CommonFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gilmour.gos.pb.FileTransProto.internal_static_pb_CommonFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gilmour.gos.pb.FileTransProto.CommonFile.class, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder.class);
    }

    private int bitField0_;
    public static final int FILEID_FIELD_NUMBER = 1;
    private volatile java.lang.Object fileID_;
    /**
     * <code>required string FileID = 1;</code>
     */
    public boolean hasFileID() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string FileID = 1;</code>
     */
    public java.lang.String getFileID() {
      java.lang.Object ref = fileID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FileID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFileIDBytes() {
      java.lang.Object ref = fileID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESIZE_FIELD_NUMBER = 2;
    private long fileSize_;
    /**
     * <code>required int64 FileSize = 2;</code>
     */
    public boolean hasFileSize() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int64 FileSize = 2;</code>
     */
    public long getFileSize() {
      return fileSize_;
    }

    public static final int FILEDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString fileData_;
    /**
     * <code>required bytes FileData = 3;</code>
     */
    public boolean hasFileData() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required bytes FileData = 3;</code>
     */
    public com.google.protobuf.ByteString getFileData() {
      return fileData_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFileID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileSize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fileID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, fileSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, fileData_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fileID_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fileSize_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, fileData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gilmour.gos.pb.FileTransProto.CommonFile)) {
        return super.equals(obj);
      }
      org.gilmour.gos.pb.FileTransProto.CommonFile other = (org.gilmour.gos.pb.FileTransProto.CommonFile) obj;

      if (hasFileID() != other.hasFileID()) return false;
      if (hasFileID()) {
        if (!getFileID()
            .equals(other.getFileID())) return false;
      }
      if (hasFileSize() != other.hasFileSize()) return false;
      if (hasFileSize()) {
        if (getFileSize()
            != other.getFileSize()) return false;
      }
      if (hasFileData() != other.hasFileData()) return false;
      if (hasFileData()) {
        if (!getFileData()
            .equals(other.getFileData())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFileID()) {
        hash = (37 * hash) + FILEID_FIELD_NUMBER;
        hash = (53 * hash) + getFileID().hashCode();
      }
      if (hasFileSize()) {
        hash = (37 * hash) + FILESIZE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFileSize());
      }
      if (hasFileData()) {
        hash = (37 * hash) + FILEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getFileData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.CommonFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gilmour.gos.pb.FileTransProto.CommonFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.CommonFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.CommonFile)
        org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_CommonFile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_CommonFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gilmour.gos.pb.FileTransProto.CommonFile.class, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder.class);
      }

      // Construct using org.gilmour.gos.pb.FileTransProto.CommonFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        fileID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        fileSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        fileData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_CommonFile_descriptor;
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.CommonFile getDefaultInstanceForType() {
        return org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance();
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.CommonFile build() {
        org.gilmour.gos.pb.FileTransProto.CommonFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.CommonFile buildPartial() {
        org.gilmour.gos.pb.FileTransProto.CommonFile result = new org.gilmour.gos.pb.FileTransProto.CommonFile(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fileID_ = fileID_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.fileSize_ = fileSize_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fileData_ = fileData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gilmour.gos.pb.FileTransProto.CommonFile) {
          return mergeFrom((org.gilmour.gos.pb.FileTransProto.CommonFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gilmour.gos.pb.FileTransProto.CommonFile other) {
        if (other == org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance()) return this;
        if (other.hasFileID()) {
          bitField0_ |= 0x00000001;
          fileID_ = other.fileID_;
          onChanged();
        }
        if (other.hasFileSize()) {
          setFileSize(other.getFileSize());
        }
        if (other.hasFileData()) {
          setFileData(other.getFileData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasFileID()) {
          return false;
        }
        if (!hasFileSize()) {
          return false;
        }
        if (!hasFileData()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gilmour.gos.pb.FileTransProto.CommonFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gilmour.gos.pb.FileTransProto.CommonFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fileID_ = "";
      /**
       * <code>required string FileID = 1;</code>
       */
      public boolean hasFileID() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string FileID = 1;</code>
       */
      public java.lang.String getFileID() {
        java.lang.Object ref = fileID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FileID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileIDBytes() {
        java.lang.Object ref = fileID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FileID = 1;</code>
       */
      public Builder setFileID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string FileID = 1;</code>
       */
      public Builder clearFileID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fileID_ = getDefaultInstance().getFileID();
        onChanged();
        return this;
      }
      /**
       * <code>required string FileID = 1;</code>
       */
      public Builder setFileIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fileID_ = value;
        onChanged();
        return this;
      }

      private long fileSize_ ;
      /**
       * <code>required int64 FileSize = 2;</code>
       */
      public boolean hasFileSize() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int64 FileSize = 2;</code>
       */
      public long getFileSize() {
        return fileSize_;
      }
      /**
       * <code>required int64 FileSize = 2;</code>
       */
      public Builder setFileSize(long value) {
        bitField0_ |= 0x00000002;
        fileSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 FileSize = 2;</code>
       */
      public Builder clearFileSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileSize_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString fileData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes FileData = 3;</code>
       */
      public boolean hasFileData() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required bytes FileData = 3;</code>
       */
      public com.google.protobuf.ByteString getFileData() {
        return fileData_;
      }
      /**
       * <code>required bytes FileData = 3;</code>
       */
      public Builder setFileData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fileData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes FileData = 3;</code>
       */
      public Builder clearFileData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fileData_ = getDefaultInstance().getFileData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.CommonFile)
    }

    // @@protoc_insertion_point(class_scope:pb.CommonFile)
    private static final org.gilmour.gos.pb.FileTransProto.CommonFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gilmour.gos.pb.FileTransProto.CommonFile();
    }

    public static org.gilmour.gos.pb.FileTransProto.CommonFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CommonFile>
        PARSER = new com.google.protobuf.AbstractParser<CommonFile>() {
      @java.lang.Override
      public CommonFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommonFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommonFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommonFile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gilmour.gos.pb.FileTransProto.CommonFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.FileRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
     */
    boolean hasOperation();
    /**
     * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
     */
    org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation getOperation();

    /**
     * <code>required string FileID = 2;</code>
     */
    boolean hasFileID();
    /**
     * <code>required string FileID = 2;</code>
     */
    java.lang.String getFileID();
    /**
     * <code>required string FileID = 2;</code>
     */
    com.google.protobuf.ByteString
        getFileIDBytes();

    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    boolean hasFile();
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    org.gilmour.gos.pb.FileTransProto.CommonFile getFile();
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder getFileOrBuilder();
  }
  /**
   * Protobuf type {@code pb.FileRequest}
   */
  public  static final class FileRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.FileRequest)
      FileRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileRequest.newBuilder() to construct.
    private FileRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileRequest() {
      operation_ = 0;
      fileID_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation value = org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                operation_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              fileID_ = bs;
              break;
            }
            case 26: {
              org.gilmour.gos.pb.FileTransProto.CommonFile.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = file_.toBuilder();
              }
              file_ = input.readMessage(org.gilmour.gos.pb.FileTransProto.CommonFile.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(file_);
                file_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gilmour.gos.pb.FileTransProto.FileRequest.class, org.gilmour.gos.pb.FileTransProto.FileRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.FileRequest.FileOperation}
     */
    public enum FileOperation
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GET = 0;</code>
       */
      GET(0),
      /**
       * <code>PUT = 1;</code>
       */
      PUT(1),
      ;

      /**
       * <code>GET = 0;</code>
       */
      public static final int GET_VALUE = 0;
      /**
       * <code>PUT = 1;</code>
       */
      public static final int PUT_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static FileOperation valueOf(int value) {
        return forNumber(value);
      }

      public static FileOperation forNumber(int value) {
        switch (value) {
          case 0: return GET;
          case 1: return PUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FileOperation>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          FileOperation> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FileOperation>() {
              public FileOperation findValueByNumber(int number) {
                return FileOperation.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.gilmour.gos.pb.FileTransProto.FileRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final FileOperation[] VALUES = values();

      public static FileOperation valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private FileOperation(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.FileRequest.FileOperation)
    }

    private int bitField0_;
    public static final int OPERATION_FIELD_NUMBER = 1;
    private int operation_;
    /**
     * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
     */
    public org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation getOperation() {
      @SuppressWarnings("deprecation")
      org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation result = org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation.valueOf(operation_);
      return result == null ? org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation.GET : result;
    }

    public static final int FILEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileID_;
    /**
     * <code>required string FileID = 2;</code>
     */
    public boolean hasFileID() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string FileID = 2;</code>
     */
    public java.lang.String getFileID() {
      java.lang.Object ref = fileID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string FileID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFileIDBytes() {
      java.lang.Object ref = fileID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_FIELD_NUMBER = 3;
    private org.gilmour.gos.pb.FileTransProto.CommonFile file_;
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    public org.gilmour.gos.pb.FileTransProto.CommonFile getFile() {
      return file_ == null ? org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
    }
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    public org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder getFileOrBuilder() {
      return file_ == null ? org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFileID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFile()) {
        if (!getFile().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, operation_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileID_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getFile());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, operation_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileID_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFile());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gilmour.gos.pb.FileTransProto.FileRequest)) {
        return super.equals(obj);
      }
      org.gilmour.gos.pb.FileTransProto.FileRequest other = (org.gilmour.gos.pb.FileTransProto.FileRequest) obj;

      if (hasOperation() != other.hasOperation()) return false;
      if (hasOperation()) {
        if (operation_ != other.operation_) return false;
      }
      if (hasFileID() != other.hasFileID()) return false;
      if (hasFileID()) {
        if (!getFileID()
            .equals(other.getFileID())) return false;
      }
      if (hasFile() != other.hasFile()) return false;
      if (hasFile()) {
        if (!getFile()
            .equals(other.getFile())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasOperation()) {
        hash = (37 * hash) + OPERATION_FIELD_NUMBER;
        hash = (53 * hash) + operation_;
      }
      if (hasFileID()) {
        hash = (37 * hash) + FILEID_FIELD_NUMBER;
        hash = (53 * hash) + getFileID().hashCode();
      }
      if (hasFile()) {
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gilmour.gos.pb.FileTransProto.FileRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.FileRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.FileRequest)
        org.gilmour.gos.pb.FileTransProto.FileRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gilmour.gos.pb.FileTransProto.FileRequest.class, org.gilmour.gos.pb.FileTransProto.FileRequest.Builder.class);
      }

      // Construct using org.gilmour.gos.pb.FileTransProto.FileRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFileFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        operation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fileID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fileBuilder_ == null) {
          file_ = null;
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileRequest_descriptor;
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.FileRequest getDefaultInstanceForType() {
        return org.gilmour.gos.pb.FileTransProto.FileRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.FileRequest build() {
        org.gilmour.gos.pb.FileTransProto.FileRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.FileRequest buildPartial() {
        org.gilmour.gos.pb.FileTransProto.FileRequest result = new org.gilmour.gos.pb.FileTransProto.FileRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileID_ = fileID_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (fileBuilder_ == null) {
            result.file_ = file_;
          } else {
            result.file_ = fileBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gilmour.gos.pb.FileTransProto.FileRequest) {
          return mergeFrom((org.gilmour.gos.pb.FileTransProto.FileRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gilmour.gos.pb.FileTransProto.FileRequest other) {
        if (other == org.gilmour.gos.pb.FileTransProto.FileRequest.getDefaultInstance()) return this;
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasFileID()) {
          bitField0_ |= 0x00000002;
          fileID_ = other.fileID_;
          onChanged();
        }
        if (other.hasFile()) {
          mergeFile(other.getFile());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasOperation()) {
          return false;
        }
        if (!hasFileID()) {
          return false;
        }
        if (hasFile()) {
          if (!getFile().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gilmour.gos.pb.FileTransProto.FileRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gilmour.gos.pb.FileTransProto.FileRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int operation_ = 0;
      /**
       * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation getOperation() {
        @SuppressWarnings("deprecation")
        org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation result = org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation.valueOf(operation_);
        return result == null ? org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation.GET : result;
      }
      /**
       * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
       */
      public Builder setOperation(org.gilmour.gos.pb.FileTransProto.FileRequest.FileOperation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .pb.FileRequest.FileOperation operation = 1;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        operation_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object fileID_ = "";
      /**
       * <code>required string FileID = 2;</code>
       */
      public boolean hasFileID() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string FileID = 2;</code>
       */
      public java.lang.String getFileID() {
        java.lang.Object ref = fileID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string FileID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFileIDBytes() {
        java.lang.Object ref = fileID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string FileID = 2;</code>
       */
      public Builder setFileID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string FileID = 2;</code>
       */
      public Builder clearFileID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileID_ = getDefaultInstance().getFileID();
        onChanged();
        return this;
      }
      /**
       * <code>required string FileID = 2;</code>
       */
      public Builder setFileIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        fileID_ = value;
        onChanged();
        return this;
      }

      private org.gilmour.gos.pb.FileTransProto.CommonFile file_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.gilmour.gos.pb.FileTransProto.CommonFile, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder, org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder> fileBuilder_;
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public boolean hasFile() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.CommonFile getFile() {
        if (fileBuilder_ == null) {
          return file_ == null ? org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
        } else {
          return fileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder setFile(org.gilmour.gos.pb.FileTransProto.CommonFile value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          file_ = value;
          onChanged();
        } else {
          fileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder setFile(
          org.gilmour.gos.pb.FileTransProto.CommonFile.Builder builderForValue) {
        if (fileBuilder_ == null) {
          file_ = builderForValue.build();
          onChanged();
        } else {
          fileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder mergeFile(org.gilmour.gos.pb.FileTransProto.CommonFile value) {
        if (fileBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              file_ != null &&
              file_ != org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance()) {
            file_ =
              org.gilmour.gos.pb.FileTransProto.CommonFile.newBuilder(file_).mergeFrom(value).buildPartial();
          } else {
            file_ = value;
          }
          onChanged();
        } else {
          fileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder clearFile() {
        if (fileBuilder_ == null) {
          file_ = null;
          onChanged();
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.CommonFile.Builder getFileBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder getFileOrBuilder() {
        if (fileBuilder_ != null) {
          return fileBuilder_.getMessageOrBuilder();
        } else {
          return file_ == null ?
              org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
        }
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.gilmour.gos.pb.FileTransProto.CommonFile, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder, org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder> 
          getFileFieldBuilder() {
        if (fileBuilder_ == null) {
          fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.gilmour.gos.pb.FileTransProto.CommonFile, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder, org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder>(
                  getFile(),
                  getParentForChildren(),
                  isClean());
          file_ = null;
        }
        return fileBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.FileRequest)
    }

    // @@protoc_insertion_point(class_scope:pb.FileRequest)
    private static final org.gilmour.gos.pb.FileTransProto.FileRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gilmour.gos.pb.FileTransProto.FileRequest();
    }

    public static org.gilmour.gos.pb.FileTransProto.FileRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FileRequest>
        PARSER = new com.google.protobuf.AbstractParser<FileRequest>() {
      @java.lang.Override
      public FileRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gilmour.gos.pb.FileTransProto.FileRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.FileResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .pb.FileResponse.Status status = 1;</code>
     */
    boolean hasStatus();
    /**
     * <code>required .pb.FileResponse.Status status = 1;</code>
     */
    org.gilmour.gos.pb.FileTransProto.FileResponse.Status getStatus();

    /**
     * <code>optional string msg = 2;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    boolean hasFile();
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    org.gilmour.gos.pb.FileTransProto.CommonFile getFile();
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder getFileOrBuilder();
  }
  /**
   * Protobuf type {@code pb.FileResponse}
   */
  public  static final class FileResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.FileResponse)
      FileResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileResponse.newBuilder() to construct.
    private FileResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileResponse() {
      status_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              org.gilmour.gos.pb.FileTransProto.FileResponse.Status value = org.gilmour.gos.pb.FileTransProto.FileResponse.Status.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                status_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              msg_ = bs;
              break;
            }
            case 26: {
              org.gilmour.gos.pb.FileTransProto.CommonFile.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) != 0)) {
                subBuilder = file_.toBuilder();
              }
              file_ = input.readMessage(org.gilmour.gos.pb.FileTransProto.CommonFile.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(file_);
                file_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gilmour.gos.pb.FileTransProto.FileResponse.class, org.gilmour.gos.pb.FileTransProto.FileResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code pb.FileResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      /**
       * <code>Err = 1;</code>
       */
      Err(1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>Err = 1;</code>
       */
      public static final int Err_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return Err;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.gilmour.gos.pb.FileTransProto.FileResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:pb.FileResponse.Status)
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>required .pb.FileResponse.Status status = 1;</code>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required .pb.FileResponse.Status status = 1;</code>
     */
    public org.gilmour.gos.pb.FileTransProto.FileResponse.Status getStatus() {
      @SuppressWarnings("deprecation")
      org.gilmour.gos.pb.FileTransProto.FileResponse.Status result = org.gilmour.gos.pb.FileTransProto.FileResponse.Status.valueOf(status_);
      return result == null ? org.gilmour.gos.pb.FileTransProto.FileResponse.Status.OK : result;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>optional string msg = 2;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_FIELD_NUMBER = 3;
    private org.gilmour.gos.pb.FileTransProto.CommonFile file_;
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    public org.gilmour.gos.pb.FileTransProto.CommonFile getFile() {
      return file_ == null ? org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
    }
    /**
     * <code>optional .pb.CommonFile file = 3;</code>
     */
    public org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder getFileOrBuilder() {
      return file_ == null ? org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasFile()) {
        if (!getFile().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, status_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getFile());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFile());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.gilmour.gos.pb.FileTransProto.FileResponse)) {
        return super.equals(obj);
      }
      org.gilmour.gos.pb.FileTransProto.FileResponse other = (org.gilmour.gos.pb.FileTransProto.FileResponse) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (status_ != other.status_) return false;
      }
      if (hasMsg() != other.hasMsg()) return false;
      if (hasMsg()) {
        if (!getMsg()
            .equals(other.getMsg())) return false;
      }
      if (hasFile() != other.hasFile()) return false;
      if (hasFile()) {
        if (!getFile()
            .equals(other.getFile())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      if (hasMsg()) {
        hash = (37 * hash) + MSG_FIELD_NUMBER;
        hash = (53 * hash) + getMsg().hashCode();
      }
      if (hasFile()) {
        hash = (37 * hash) + FILE_FIELD_NUMBER;
        hash = (53 * hash) + getFile().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.gilmour.gos.pb.FileTransProto.FileResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.gilmour.gos.pb.FileTransProto.FileResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.FileResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.FileResponse)
        org.gilmour.gos.pb.FileTransProto.FileResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.gilmour.gos.pb.FileTransProto.FileResponse.class, org.gilmour.gos.pb.FileTransProto.FileResponse.Builder.class);
      }

      // Construct using org.gilmour.gos.pb.FileTransProto.FileResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFileFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (fileBuilder_ == null) {
          file_ = null;
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.gilmour.gos.pb.FileTransProto.internal_static_pb_FileResponse_descriptor;
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.FileResponse getDefaultInstanceForType() {
        return org.gilmour.gos.pb.FileTransProto.FileResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.FileResponse build() {
        org.gilmour.gos.pb.FileTransProto.FileResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.gilmour.gos.pb.FileTransProto.FileResponse buildPartial() {
        org.gilmour.gos.pb.FileTransProto.FileResponse result = new org.gilmour.gos.pb.FileTransProto.FileResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.status_ = status_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.msg_ = msg_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          if (fileBuilder_ == null) {
            result.file_ = file_;
          } else {
            result.file_ = fileBuilder_.build();
          }
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.gilmour.gos.pb.FileTransProto.FileResponse) {
          return mergeFrom((org.gilmour.gos.pb.FileTransProto.FileResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.gilmour.gos.pb.FileTransProto.FileResponse other) {
        if (other == org.gilmour.gos.pb.FileTransProto.FileResponse.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000002;
          msg_ = other.msg_;
          onChanged();
        }
        if (other.hasFile()) {
          mergeFile(other.getFile());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        if (hasFile()) {
          if (!getFile().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.gilmour.gos.pb.FileTransProto.FileResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.gilmour.gos.pb.FileTransProto.FileResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>required .pb.FileResponse.Status status = 1;</code>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required .pb.FileResponse.Status status = 1;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.FileResponse.Status getStatus() {
        @SuppressWarnings("deprecation")
        org.gilmour.gos.pb.FileTransProto.FileResponse.Status result = org.gilmour.gos.pb.FileTransProto.FileResponse.Status.valueOf(status_);
        return result == null ? org.gilmour.gos.pb.FileTransProto.FileResponse.Status.OK : result;
      }
      /**
       * <code>required .pb.FileResponse.Status status = 1;</code>
       */
      public Builder setStatus(org.gilmour.gos.pb.FileTransProto.FileResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .pb.FileResponse.Status status = 1;</code>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 2;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 2;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        msg_ = value;
        onChanged();
        return this;
      }

      private org.gilmour.gos.pb.FileTransProto.CommonFile file_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.gilmour.gos.pb.FileTransProto.CommonFile, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder, org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder> fileBuilder_;
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public boolean hasFile() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.CommonFile getFile() {
        if (fileBuilder_ == null) {
          return file_ == null ? org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
        } else {
          return fileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder setFile(org.gilmour.gos.pb.FileTransProto.CommonFile value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          file_ = value;
          onChanged();
        } else {
          fileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder setFile(
          org.gilmour.gos.pb.FileTransProto.CommonFile.Builder builderForValue) {
        if (fileBuilder_ == null) {
          file_ = builderForValue.build();
          onChanged();
        } else {
          fileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder mergeFile(org.gilmour.gos.pb.FileTransProto.CommonFile value) {
        if (fileBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
              file_ != null &&
              file_ != org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance()) {
            file_ =
              org.gilmour.gos.pb.FileTransProto.CommonFile.newBuilder(file_).mergeFrom(value).buildPartial();
          } else {
            file_ = value;
          }
          onChanged();
        } else {
          fileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public Builder clearFile() {
        if (fileBuilder_ == null) {
          file_ = null;
          onChanged();
        } else {
          fileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.CommonFile.Builder getFileBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      public org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder getFileOrBuilder() {
        if (fileBuilder_ != null) {
          return fileBuilder_.getMessageOrBuilder();
        } else {
          return file_ == null ?
              org.gilmour.gos.pb.FileTransProto.CommonFile.getDefaultInstance() : file_;
        }
      }
      /**
       * <code>optional .pb.CommonFile file = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.gilmour.gos.pb.FileTransProto.CommonFile, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder, org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder> 
          getFileFieldBuilder() {
        if (fileBuilder_ == null) {
          fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.gilmour.gos.pb.FileTransProto.CommonFile, org.gilmour.gos.pb.FileTransProto.CommonFile.Builder, org.gilmour.gos.pb.FileTransProto.CommonFileOrBuilder>(
                  getFile(),
                  getParentForChildren(),
                  isClean());
          file_ = null;
        }
        return fileBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.FileResponse)
    }

    // @@protoc_insertion_point(class_scope:pb.FileResponse)
    private static final org.gilmour.gos.pb.FileTransProto.FileResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.gilmour.gos.pb.FileTransProto.FileResponse();
    }

    public static org.gilmour.gos.pb.FileTransProto.FileResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FileResponse>
        PARSER = new com.google.protobuf.AbstractParser<FileResponse>() {
      @java.lang.Override
      public FileResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.gilmour.gos.pb.FileTransProto.FileResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_CommonFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_CommonFile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_FileRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_FileRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_FileResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_FileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017fileTrans.proto\022\002pb\"@\n\nCommonFile\022\016\n\006F" +
      "ileID\030\001 \002(\t\022\020\n\010FileSize\030\002 \002(\003\022\020\n\010FileDat" +
      "a\030\003 \002(\014\"\220\001\n\013FileRequest\0220\n\toperation\030\001 \002" +
      "(\0162\035.pb.FileRequest.FileOperation\022\016\n\006Fil" +
      "eID\030\002 \002(\t\022\034\n\004file\030\003 \001(\0132\016.pb.CommonFile\"" +
      "!\n\rFileOperation\022\007\n\003GET\020\000\022\007\n\003PUT\020\001\"}\n\014Fi" +
      "leResponse\022\'\n\006status\030\001 \002(\0162\027.pb.FileResp" +
      "onse.Status\022\013\n\003msg\030\002 \001(\t\022\034\n\004file\030\003 \001(\0132\016" +
      ".pb.CommonFile\"\031\n\006Status\022\006\n\002OK\020\000\022\007\n\003Err\020" +
      "\001B$\n\022org.gilmour.gos.pbB\016FileTransProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pb_CommonFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_CommonFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_CommonFile_descriptor,
        new java.lang.String[] { "FileID", "FileSize", "FileData", });
    internal_static_pb_FileRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_FileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_FileRequest_descriptor,
        new java.lang.String[] { "Operation", "FileID", "File", });
    internal_static_pb_FileResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_pb_FileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_FileResponse_descriptor,
        new java.lang.String[] { "Status", "Msg", "File", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
